### ISSUE TITLE
Generator script not working

### ISSUE THREAD

**Issue by killchainrepo** [Azure-Samples/ai-rag-chat-evaluator#58]
Trying to run the generator script and it doesn't work. I am using Azure openai/Ai search for index/code space for testing.
Please help if possible

- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure

>05:06:56 (INFO) scripts: Using Azure OpenAI Service with Azure Developer CLI Credential
05:06:56 (INFO) azure.identity._internal.decorators: AzureDeveloperCliCredential.get_token succeeded
05:06:56 (INFO) scripts: Using Azure Search Service with API Key from AZURE_SEARCH_KEY
05:06:56 (INFO) scripts: Generating 50 questions total, 5 per source, based on search results
05:06:56 (INFO) azure.core.pipeline.policies.http_logging_policy: Request URL: 'https://testservcie3.search.windows.net/indexes('index12')/docs/search.post.search?api-version=REDACTED'
Request method: 'POST'
Request headers:
    'Content-Type': 'application/json'
    'Content-Length': '27'
    'api-key': 'REDACTED'
    'Accept': 'application/json;odata.metadata=none'
    'x-ms-client-request-id': '822ae6a6-e5ae-11ee-8800-000d3acb1738'
    'User-Agent': 'azsdk-python-search-documents/11.4.0 Python/3.11.8 (Linux-6.2.0-1019-azure-x86_64-with-glibc2.31)'
A body is sent with the request
05:06:56 (INFO) azure.core.pipeline.policies.http_logging_policy: Response status: 200
Response headers:
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json; odata.metadata=none; odata.streaming=true; charset=utf-8'
    'Content-Encoding': 'REDACTED'
    'Vary': 'REDACTED'
    'Server': 'Microsoft-IIS/10.0'
    'Strict-Transport-Security': 'REDACTED'
    'Preference-Applied': 'REDACTED'
    'OData-Version': 'REDACTED'
    'request-id': '822ae6a6-e5ae-11ee-8800-000d3acb1738'
    'elapsed-time': 'REDACTED'
    'Date': 'Tue, 19 Mar 2024 05:06:56 GMT'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspaces/ai-rag-chat-evaluator/scripts/__main__.py", line 6, in <module>
    app()
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
           ^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ai-rag-chat-evaluator/scripts/cli.py", line 40, in generate
    generate_test_qa_data(
  File "/workspaces/ai-rag-chat-evaluator/scripts/generate.py", line 37, in generate_test_qa_data
    logger.info("Processing search document %s", doc["sourcepage"])

### Expected/desired behavior
>na

### OS and Version?
windows 10 VM 



### Mention any other details that might be useful
na

**Comment by pamelafox** [comment]
Hm, it seems like the final error code is cut off, but I'm wondering if your search fields are different than its expecting. What fields are in your index?

**Comment by killchainrepo** [comment]
Hi Pamela

Thanks for looking into this 

So the final error code is : KeyError: 'sourcepage' .Sorry for missing this one.

Attaching the Azure ai search field screenshot. Does the generator script requires particular field values?

![FieldIndex12](https://github.com/Azure-Samples/ai-rag-chat-evaluator/assets/99376811/65b6275a-3c27-4947-96cd-93d6e2fbee2b)

**Comment by killchainrepo** [comment]
Thanks so much Pamela. It works now.

**Comment by jakeatmsft** [comment]
Open PR, to make the citation field name configurable: #96

**Comment by pamelafox** [comment]
Closing this issue now, thanks @jakeatmsft !
