### ISSUE TITLE
Evaluate fails using openai.com instance 

### ISSUE THREAD

**Issue by reedrefucher** [Azure-Samples/ai-rag-chat-evaluator#61]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Follow https://github.com/Azure-Samples/azure-search-openai-demo to launch local copy of the backend app, using openai deployment (not Azure openai).
2. Clone this repo, setup dev container and set environmental variables in accordance with https://github.com/Azure-Samples/ai-rag-chat-evaluator?tab=readme-ov-file#using-an-openaicom-instance. 
3. Launch evaluate with the next config: 
`{
    "api_type": "openai",
    "testdata_path": "example_input/qa.jsonl",
    "results_dir": "example_results/experiment<TIMESTAMP>",
    "requested_metrics": ["gpt_groundedness", "gpt_relevance", "gpt_coherence", "answer_length", "latency"],
    "target_url": "http://host.docker.internal:50505/chat",
    "target_parameters": {
        "overrides": {
            "semantic_ranker": false,
            "prompt_template": "<READFILE>example_input/prompt_refined.txt"
        }
    },
    "model": "gpt-3.5-turbo"
}` 

###  Log trace
$ python -m scripts evaluate --config=example_config.json
17:44:10 (INFO) scripts: Running evaluation from config /workspaces/ai-rag-chat-evaluator/example_config.json
17:44:10 (INFO) scripts: Replaced results_dir in config with timestamp
17:44:10 (INFO) scripts: Replaced prompt_template in config with contents of example_input/prompt_refined.txt
17:44:10 (INFO) scripts: Using OpenAI Service with API Key from OPENAICOM_KEY
17:44:10 (INFO) scripts: Running evaluation using data from /workspaces/ai-rag-chat-evaluator/example_input/qa.jsonl
17:44:10 (INFO) scripts: Sending a test question to the target to ensure it is running...
17:44:17 (INFO) scripts: Successfully received response from target: "question": "What information is in your kn...", "answer": "What would you like to know?", "context": "SUBSET-026-2 v360.pdf#page=9: ..."
17:44:17 (INFO) scripts: Sending a test chat completion to the GPT deployment to ensure it is running...
17:44:19 (INFO) httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
17:44:19 (INFO) scripts: Successfully received response from GPT: Hello! How can I assist you today?
17:44:19 (INFO) scripts: Starting evaluation...
Fail writing properties '{'_azureml.evaluation_run': 'azure-ai-generative-parent'}' to run history: 'FileStore' object has no attribute 'get_host_creds'
Calculating code metrics : ['answer_length', 'latency']
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 20.79it/s]
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/azure/ai/generative/evaluate/_evaluate.py", line 359, in _evaluate
    inbuilt_metrics_results = inbuilt_metrics_handler.calculate_metrics()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/azure/ai/generative/evaluate/_metric_handler.py", line 82, in calculate_metrics
    deployment_id = openai_config["deployment_id"]
                    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'deployment_id'

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspaces/ai-rag-chat-evaluator/scripts/__main__.py", line 6, in <module>
    app()
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/core.py", line 783, in main
    return _main(
           ^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/core.py", line 225, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/main.py", line 685, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ai-rag-chat-evaluator/scripts/cli.py", line 31, in evaluate
    run_evaluate_from_config(Path.cwd(), config, numquestions)
  File "/workspaces/ai-rag-chat-evaluator/scripts/evaluate.py", line 196, in run_evaluate_from_config
    evaluation_run_complete = run_evaluation(
                              ^^^^^^^^^^^^^^^
  File "/workspaces/ai-rag-chat-evaluator/scripts/evaluate.py", line 121, in run_evaluation
    results = evaluate(
              ^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/azure/ai/ml/_telemetry/activity.py", line 291, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/azure/ai/generative/evaluate/_evaluate.py", line 237, in evaluate
    evaluation_result = _evaluate(
                        ^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/azure/ai/generative/evaluate/_evaluate.py", line 359, in _evaluate
    inbuilt_metrics_results = inbuilt_metrics_handler.calculate_metrics()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/azure/ai/generative/evaluate/_metric_handler.py", line 82, in calculate_metrics
    deployment_id = openai_config["deployment_id"]
                    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'deployment_id'

### Expected/desired behavior
Evaluation completes just like in the video: https://www.youtube.com/watch?v=mM8pZAI2C5w

### OS and Version?
macOS 14.3.1 (23D60)

### Mention any other details that might be useful
I traced the line causing an error in the azure sdk (see https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ai/azure-ai-generative/azure/ai/generative/evaluate/_metric_handler.py). It seems that the code expects an instance of https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/ai/azure-ai-resources/azure/ai/resources/entities/configs.py, but when I inspect it, it refers to Azure deployments only. 
Am I missing something when trying to evaluate using openai.api?

**Comment by pamelafox** [comment]
Sorry I haven't had a chance to debug this yet, will look tomorrow!
