### ISSUE TITLE
Connection error when running generator script

### ISSUE THREAD

**Issue by rialtolabs-lit** [Azure-Samples/ai-rag-chat-evaluator#66]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
21:13:11 (INFO) scripts: Using Azure OpenAI Service with Azure Developer CLI Credential
21:13:11 (INFO) azure.identity._internal.decorators: AzureDeveloperCliCredential.get_token succeeded
21:13:11 (INFO) scripts: Using Azure Search Service with Azure Developer CLI Credential
21:13:11 (INFO) scripts: Generating 200 questions total, 5 per source, based on search results
21:13:11 (INFO) azure.identity._internal.decorators: AzureDeveloperCliCredential.get_token succeeded
21:13:11 (INFO) azure.core.pipeline.policies.http_logging_policy: Request URL: 'https://gptkb-tmvqzfxi3p3jc.search.windows.net/indexes('gptkbindex')/docs/search.post.search?api-version=REDACTED'
Request method: 'POST'
Request headers:
    'Content-Type': 'application/json'
    'Content-Length': '27'
    'Accept': 'application/json'
    'x-ms-client-request-id': 'fa39de84-f1fe-11ee-bbb8-002248870ddc'
    'User-Agent': 'azsdk-python-search-documents/11.4.0 Python/3.11.8 (Linux-6.2.0-1019-azure-x86_64-with-glibc2.31)'
    'Authorization': 'REDACTED'
A body is sent with the request
21:13:15 (INFO) azure.core.pipeline.policies.http_logging_policy: Response status: 200
Response headers:
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8'
    'Content-Encoding': 'REDACTED'
    'Vary': 'REDACTED'
    'Server': 'Microsoft-IIS/10.0'
    'Strict-Transport-Security': 'REDACTED'
    'Preference-Applied': 'REDACTED'
    'OData-Version': 'REDACTED'
    'request-id': 'fa39de84-f1fe-11ee-bbb8-002248870ddc'
    'elapsed-time': 'REDACTED'
    'Date': 'Wed, 03 Apr 2024 21:13:13 GMT'
21:13:15 (INFO) scripts: Processing search document Yan Calibration Transfer and drift compensation e noses via coupled task learning 2015.pdf#page=1
21:13:15 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 0.979383 seconds
21:13:16 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 1.683232 seconds
21:13:20 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 0.990305 seconds
21:13:21 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 1.640511 seconds
21:13:27 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 0.801224 seconds
21:13:27 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 1.739024 seconds
21:13:37 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 0.890408 seconds
21:13:38 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 1.806998 seconds
21:13:56 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 0.803116 seconds
21:13:57 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 1.692248 seconds
21:14:30 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 0.972259 seconds
21:14:31 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 1.619241 seconds
21:15:37 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 0.946597 seconds
21:15:38 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 1.540704 seconds
21:17:48 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 0.822784 seconds
21:17:48 (INFO) openai._base_client: Retrying request to /deployments/<deployment-name>/chat/completions in 1.631186 seconds
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/vscode/.local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/vscode/.local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/vscode/.local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/vscode/.local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/openai/_base_client.py", line 931, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/vscode/.local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspaces/ai-rag-chat-evaluator/scripts/__main__.py", line 6, in <module>
    app()
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/main.py", line 326, in __call__
    raise e
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/core.py", line 723, in main
    return _main(
           ^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/typer/main.py", line 688, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ai-rag-chat-evaluator/scripts/cli.py", line 40, in generate
    generate_test_qa_data(
  File "/workspaces/ai-rag-chat-evaluator/scripts/generate.py", line 40, in generate_test_qa_data
    result = qa_generator.generate(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/azure/ai/ml/_telemetry/activity.py", line 291, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/azure/ai/generative/synthetic/qa.py", line 397, in generate
    content, token_usage = _completion_with_retries(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/azure/ai/generative/synthetic/qa.py", line 69, in _completion_with_retries
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1213, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/openai/_base_client.py", line 902, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/openai/_base_client.py", line 955, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1026, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/openai/_base_client.py", line 955, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1026, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/openai/_base_client.py", line 965, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

### Expected/desired behavior
>

### OS and Version?
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by BlockchainRev** [comment]
I am also facing a similar issue.
`[03:37:30] INFO     Running evaluation from config /workspaces/ai-rag-chat-evaluator/example_config.json                                         evaluate.py:195
           INFO     Replaced results_dir in config with timestamp                                                                                evaluate.py:185
           INFO     Replaced prompt_template in config with contents of example_input/prompt_refined.txt                                         evaluate.py:189
           INFO     Using OpenAI Service with API Key from OPENAICOM_KEY                                                                     service_setup.py:30
           INFO     Running evaluation using data from /workspaces/ai-rag-chat-evaluator/example_input/qa.jsonl                                   evaluate.py:80
           INFO     Sending a test question to the target to ensure it is running...                                                              evaluate.py:86
           ERROR    Failed to send a test question to the target due to error:                                                                    evaluate.py:98
                    HTTPConnectionPool(host='localhost', port=50505): Max retries exceeded with url: /chat (Caused by                                           
                    NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe3f0effd50>: Failed to establish a new connection:                     
                    [Errno 111] Connection refused'))      `

**Comment by pamelafox** [comment]
@BlockchainRev That error indicates that it's trying to send a request to localhost:50505/chat, but not getting a response.

Do you definitely have the server running at that URL?
If you're running ai-rag-chat-evaluator in the dev container, you'll need to change `localhost` to `host.docker.internal`, as noted in the README.
And if your server is deployed, you'll need to change localhost to the domain and http to https.

**Comment by pamelafox** [comment]
Also, one thing that I find helpful in debugging OpenAI connections is to set the logging level to DEBUG, since the OpenAI SDK displays what URL its connecting to. You can change the level in  cli.py:

```
logging.basicConfig(
    level=logging.DEBUG, format="%(message)s", datefmt="[%X]", handlers=[RichHandler(rich_tracebacks=True)]
)
```

Let me know what your issue ends up being, as I may be able to add in helpful debugging messages. Thanks!
